### ISSUE TITLE
helloe

### ISSUE THREAD

**Issue by glerinsonum** [wells/airflix#10]
@wells can install this in wordpress.

**Comment by glerinsonum** [comment]
403 Forbidden
nginx/1.11.8


Warning: require(C:\nginx\html\airflix\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\nginx\html\airflix\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\nginx\html\airflix\bootstrap/../vendor/autoload.php' (include_path='.;C:\php\pear') in C:\nginx\html\airflix\bootstrap\autoload.php on line 17

**Comment by wells** [comment]
Hi @glerinsonum. Again, this is not a Wordpress plugin. This is a self contained application that runs on the Laravel framework. See https://laravel.com/docs to learn how to try this out.
