### ISSUE TITLE
allow more than one file extension?

### ISSUE THREAD

**Issue by formatme** [wells/airflix#13]
Can you allow more than one file extension
or will this work
   'extensions' => [
        'video' => env('AIRFLIX_EXTENSIONS_VIDEO', 'm4v'),
         'video' => env('AIRFLIX_EXTENSIONS_VIDEO', 'mp4'),
    ],

**Comment by wells** [comment]
No worries. I have added support for multiple video file extensions in the latest `v1.1.6` release.

It now defaults to `"m4v, mp4"`, which gives preference to stream m4v iTunes files over mp4 files if the m4v exists. You can add any other extensions and/or change the order of the comma separated list, by editing the value of `AIRFLIX_EXTENSIONS_VIDEO` in your `.env` file.
