### ISSUE TITLE
Running project

### ISSUE THREAD

**Issue by ghost** [wells/airflix#16]
Hi, installation was fine - no errors whatsoever.
Although there are no docs about running the project itself, i tried to use php artisan:serve, it returns me the message the website is now available on localhost:8000 although i can't access it?

**Comment by wells** [comment]
I have been unable to replicate the issue on my local development environment. See below.

I would also recommend you install Laravel Valet for testing the application, but `artisan serve` should also work out the gate. FYI, I intend to release some updates to the project this week (i.e. Laravel 5.6, local web fonts, and more).

https://laravel.com/docs/5.6/valet

```
☁  airflix [master]  artisan serve

Laravel development server started: <http://127.0.0.1:8000>

[Tue Jul  3 10:12:54 2018] 127.0.0.1:50198 [200]: /css/app.css
[Tue Jul  3 10:12:54 2018] 127.0.0.1:50201 [200]: /js/manifest.js
[Tue Jul  3 10:12:54 2018] 127.0.0.1:50202 [200]: /js/vendor.js
[Tue Jul  3 10:12:54 2018] 127.0.0.1:50203 [200]: /js/app.js
[Tue Jul  3 10:12:54 2018] 127.0.0.1:50208 [200]: /fonts/opensans/v15/mem5YaGs126MiZpBA-UN8rsOUuhpKKSTjw.woff2
[Tue Jul  3 10:12:54 2018] 127.0.0.1:50209 [200]: /fonts/materialicons/v38/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2
[Tue Jul  3 10:12:54 2018] 127.0.0.1:50210 [200]: /fonts/opensans/v15/mem8YaGs126MiZpBA-UFVZ0bf8pkAg.woff2
[Tue Jul  3 10:12:54 2018] 127.0.0.1:50212 [200]: /fonts/opensans/v15/mem5YaGs126MiZpBA-UN_r8OUuhpKKSTjw.woff2
[Tue Jul  3 10:12:54 2018] 127.0.0.1:50213 [200]: /touch-icon-iphone.png
```
