### ISSUE TITLE
@wells

### ISSUE THREAD

**Issue by glerinsonum** [wells/airflix#9]
@wells Installing Theme from uploaded file: airflix-master.zip
Unpacking the package…

Installing the theme…

The package could not be installed. The theme is missing the style.css stylesheet.

Theme install failed.

**Comment by wells** [comment]
What theme are you referring to? This is a complete JS / php application that relies on a database and is installed via composer. This is not an extension to another platform or a theme for a blog.

Current production CSS file can be found at:
https://github.com/wells/airflix/tree/master/public/build/css

Original SASS files can be found at:
https://github.com/wells/airflix/tree/master/resources/assets/sass
